# Generated by Django 6.1 on 2026-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_transaction_receiver_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
