
# Generated by Django 6.1 on 2026-08-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
            ),
        ),
    ]