# Generated by Django 6.1 on 2026-08-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_wallet_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
