# Generated by Django 6.1 on 2026-08-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_walletfunding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletFunding',
        ),
    ]
