# Generated by Django 6.1 on 2026-08-26 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_schoolfeepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUGPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sug_payments', to='students.student')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sug_payments', to='students.wallet')),
            ],
        ),
    ]
