# Generated by Django 6.1 on 2026-08-27 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_wallet_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=10, unique=True)),
                ('account_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_bank_account', to='students.student')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_bank_account', to='students.wallet')),
            ],
        ),
    ]
